<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Seeder;

class AgentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing agents

        $agents = [
            [
                'user_id' => 1,
                'agent_name' => 'Rajesh Kumar',
                'agent_email' => 'rajesh.kumar@example.com',
                'agent_phone' => '9876543210',
                'agent_code' => 'AGT001',
                'address' => '123 MG Road',
                'city' => 'Mumbai',
                'district' => 'Mumbai Suburban',
                'state' => 'Maharashtra',
                'pincode' => '400001',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Priya Sharma',
                'agent_email' => 'priya.sharma@example.com',
                'agent_phone' => '9876543211',
                'agent_code' => 'AGT002',
                'address' => '456 Park Street',
                'city' => 'Kolkata',
                'district' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700016',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Amit Patel',
                'agent_email' => 'amit.patel@example.com',
                'agent_phone' => '9876543212',
                'agent_code' => 'AGT003',
                'address' => '789 CG Road',
                'city' => 'Ahmedabad',
                'district' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380009',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Sneha Reddy',
                'agent_email' => 'sneha.reddy@example.com',
                'agent_phone' => '9876543213',
                'agent_code' => 'AGT004',
                'address' => '321 Banjara Hills',
                'city' => 'Hyderabad',
                'district' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'status' => 'inactive',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Vikram Singh',
                'agent_email' => 'vikram.singh@example.com',
                'agent_phone' => '9876543214',
                'agent_code' => 'AGT005',
                'address' => '654 Connaught Place',
                'city' => 'New Delhi',
                'district' => 'Central Delhi',
                'state' => 'Delhi',
                'pincode' => '110001',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Anita Desai',
                'agent_email' => 'anita.desai@example.com',
                'agent_phone' => '9876543215',
                'agent_code' => 'AGT006',
                'address' => '987 Brigade Road',
                'city' => 'Bangalore',
                'district' => 'Bangalore Urban',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Rahul Verma',
                'agent_email' => 'rahul.verma@example.com',
                'agent_phone' => '9876543216',
                'agent_code' => 'AGT007',
                'address' => '147 Anna Salai',
                'city' => 'Chennai',
                'district' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600002',
                'status' => 'inactive',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Kavita Nair',
                'agent_email' => 'kavita.nair@example.com',
                'agent_phone' => '9876543217',
                'agent_code' => 'AGT008',
                'address' => '258 MG Road',
                'city' => 'Kochi',
                'district' => 'Ernakulam',
                'state' => 'Kerala',
                'pincode' => '682016',
                'status' => 'inactive',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Suresh Iyer',
                'agent_email' => 'suresh.iyer@example.com',
                'agent_phone' => '9876543218',
                'agent_code' => 'AGT009',
                'address' => '369 FC Road',
                'city' => 'Pune',
                'district' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411004',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Meera Joshi',
                'agent_email' => 'meera.joshi@example.com',
                'agent_phone' => '9876543219',
                'agent_code' => 'AGT010',
                'address' => '741 MI Road',
                'city' => 'Jaipur',
                'district' => 'Jaipur',
                'state' => 'Rajasthan',
                'pincode' => '302001',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Arjun Mehta',
                'agent_email' => 'arjun.mehta@example.com',
                'agent_phone' => '9876543220',
                'agent_code' => 'AGT011',
                'address' => '852 Mall Road',
                'city' => 'Chandigarh',
                'district' => 'Chandigarh',
                'state' => 'Chandigarh',
                'pincode' => '160001',
                'status' => 'inactive',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Deepa Rao',
                'agent_email' => 'deepa.rao@example.com',
                'agent_phone' => '9876543221',
                'agent_code' => 'AGT012',
                'address' => '963 Residency Road',
                'city' => 'Indore',
                'district' => 'Indore',
                'state' => 'Madhya Pradesh',
                'pincode' => '452001',
                'status' => 'inactive',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Karan Kapoor',
                'agent_email' => 'karan.kapoor@example.com',
                'agent_phone' => '9876543222',
                'agent_code' => 'AGT013',
                'address' => '159 Station Road',
                'city' => 'Lucknow',
                'district' => 'Lucknow',
                'state' => 'Uttar Pradesh',
                'pincode' => '226001',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Pooja Gupta',
                'agent_email' => 'pooja.gupta@example.com',
                'agent_phone' => '9876543223',
                'agent_code' => 'AGT014',
                'address' => '753 Park Road',
                'city' => 'Bhopal',
                'district' => 'Bhopal',
                'state' => 'Madhya Pradesh',
                'pincode' => '462001',
                'status' => 'active',
            ],
            [
                'user_id' => 1,
                'agent_name' => 'Nikhil Saxena',
                'agent_email' => 'nikhil.saxena@example.com',
                'agent_phone' => '9876543224',
                'agent_code' => 'AGT015',
                'address' => '357 Civil Lines',
                'city' => 'Nagpur',
                'district' => 'Nagpur',
                'state' => 'Maharashtra',
                'pincode' => '440001',
                'status' => 'inactive',
            ],
        ];

        foreach ($agents as $agentData) {
            Agent::updateOrCreate(
                ['agent_code' => $agentData['agent_code']],
                [
                    'user_id'     => $agentData['user_id'],
                    'agent_name'  => $agentData['agent_name'],
                    'agent_phone' => $agentData['agent_phone'],
                    'status'      => $agentData['status'] ?? 'active',
                ]
            );
        }

    }
}
