<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Credit Report') }} - {{ $row->applicant_name }}</title>
    <style>
        @page { margin: 40px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12px; color: #333; line-height: 1.5; margin: 0; padding: 0; }
        .header { border-bottom: 2px solid #0d6efd; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #0d6efd; text-transform: uppercase; }
        .report-title { float: right; text-align: right; color: #666; }
        .report-title h1 { margin: 0; font-size: 20px; color: #333; }
        .clearfix { clear: both; }
        
        .score-container { background: #f8f9fa; border-radius: 8px; padding: 30px; margin-bottom: 30px; text-align: center; border: 1px solid #dee2e6; }
        .score-box { display: inline-block; padding: 20px 40px; border-radius: 12px; margin-bottom: 15px; }
        .score-value { font-size: 48px; font-weight: bold; margin: 0; line-height: 1; }
        .score-label { font-size: 16px; font-weight: bold; text-transform: uppercase; margin-top: 5px; }
        
        /* Score Colors */
        .score-excellent { background-color: #d1e7dd; color: #0f5132; border: 2px solid #badbcc; }
        .score-good { background-color: #fff3cd; color: #856404; border: 2px solid #ffeeba; }
        .score-fair { background-color: #fff3cd; color: #856404; border: 2px solid #ffeeba; }
        .score-poor { background-color: #f8d7da; color: #842029; border: 2px solid #f5c2c7; }
        
        .section-title { background: #eee; padding: 8px 12px; font-weight: bold; margin-bottom: 15px; border-left: 4px solid #0d6efd; text-transform: uppercase; font-size: 13px; }
        .info-grid { width: 100%; margin-bottom: 30px; }
        .info-grid td { padding: 8px 0; border-bottom: 1px solid #eee; vertical-align: top; }
        .label { color: #666; font-weight: bold; width: 35%; }
        .value { color: #000; }
        
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="report-title">
            <h1>CREDIT SCORE REPORT</h1>
            <div>Reference ID: #{{ $row->id }}-{{ now()->format('Ymd') }}</div>
            <div>Generated on: {{ now()->format('d-m-Y h:i A') }}</div>
        </div>
        <div class="logo">{{ config('app.name') }}</div>
        <div class="clearfix"></div>
    </div>

    @php
        $scoreClass = 'score-poor';
        if($row->score >= 750) $scoreClass = 'score-excellent';
        elseif($row->score >= 700) $scoreClass = 'score-good';
        elseif($row->score >= 650) $scoreClass = 'score-fair';
    @endphp

    <div class="score-container">
        <div class="score-box {{ $scoreClass }}">
            <div class="score-value">{{ $row->score ?? 'N/A' }}</div>
            <div class="score-label">{{ $row->rating ?? 'No Rating' }}</div>
        </div>
        <p style="margin: 0; color: #666;">This score represents your creditworthiness based on our bureau partner data.</p>
    </div>

    <div class="section-title">Personal Information</div>
    <table class="info-grid">
        <tr>
            <td class="label">Full Name</td>
            <td class="value">{{ $row->applicant_name }}</td>
        </tr>
        <tr>
            <td class="label">Aadhaar Number</td>
            <td class="value">XXXXXXXX{{ strlen($row->aadhar_number) > 4 ? substr($row->aadhar_number, -4) : 'XXXX' }}</td>
        </tr>
        <tr>
            <td class="label">PAN Number</td>
            <td class="value">{{ $row->pan_number ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Email Address</td>
            <td class="value">{{ $row->email ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Mobile Number</td>
            <td class="value">{{ $row->phone ?? 'N/A' }}</td>
        </tr>
    </table>

    <div class="section-title">Verification Details</div>
    <table class="info-grid">
        <tr>
            <td class="label">Identity Status</td>
            <td class="value">
                <span style="color: green; font-weight: bold;">✔ Verified via Aadhaar OTP</span>
            </td>
        </tr>
        <tr>
            <td class="label">Bureau Status</td>
            <td class="value">{{ ucfirst($row->status) }}</td>
        </tr>
        @if($row->client_id)
        <tr>
            <td class="label">Registered Client</td>
            <td class="value">{{ $row->client->client_name }}</td>
        </tr>
        @endif
    </table>

    <div class="footer">
        This document is a confidential electronic report generated by {{ config('app.name') }}. 
        © {{ date('Y') }} {{ config('app.name') }}. All rights reserved.
    </div>
</body>
</html>
